services:
  php:
    build: .
    container_name: php_app2
    ports:
      - "3003:80"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app_network2
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    restart: unless-stopped

  mysql:
    image: mysql:5.7
    container_name: mysql_db2
    environment:
      MYSQL_ROOT_PASSWORD: Testing
      MYSQL_DATABASE: demo_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./employees.sql:/docker-entrypoint-initdb.d/employees.sql
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    networks:
      - app_network2
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-pTesting"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  app_network2:
    driver: bridge

volumes:
  mysql_data2:
    driver: local
